### ISSUE TITLE
Error: All columns in a tibble must be 1d or 2d objects: * Column `thomas` is NULL

### ISSUE THREAD

**Issue by doctor-phil** [briatte/congress#2]
Hello,

I see that you have not updated this in a while. I think this issue may be due to a new congressperson?

Anyway, I am desperately searching for network data from the US senate and house of representatives (specifically the 110-112 congress). When I run your code, I get the following error:
Error: All columns in a tibble must be 1d or 2d objects:
* Column `thomas` is NULL

followed by another error from the 02-build.r script:
Error in filter(s, mandate == jj) : object 's' not found

I will paste the full output with backtrace below.

Thanks

```
> library(jsonlite) # read JSON data
> library(yaml)     # read YAML data
> library(dplyr)    # data manipulation
> library(stringr)  # strings manipulation
> library(network)  # network manipulation
> 
> dir.create("data"  , showWarnings = FALSE)
> dir.create("plots" , showWarnings = FALSE)
> 
> source("01-data.r")  # data collection
Congress 114: loaded 10916 bills...
Congress 113: loaded 10637 bills...
Congress 112: loaded 12299 bills...
Congress 111: loaded 13674 bills...
Congress 110: loaded 14040 bills...
Congress 109: loaded 13071 bills...
Congress 108: loaded 10667 bills...
Congress 107: loaded 10789 bills...
Congress 106: loaded 10838 bills...
Congress 105: loaded 9141 bills...
Congress 104: loaded 7991 bills...
Congress 103: loaded 9821 bills...
Congress 102: loaded 12014 bills...
Congress 101: loaded 11786 bills...
Congress 100: loaded 11277 bills...
Congress 99: loaded 11599 bills...
Congress 98: loaded 12200 bills...
Congress 97: loaded 13232 bills...
Congress 96: loaded 14587 bills...
Congress 95: loaded 22313 bills...
Congress 94: loaded 24285 bills...
Congress 93: loaded 26222 bills...
Error: All columns in a tibble must be 1d or 2d objects:
* Column `thomas` is NULL
Call `rlang::last_error()` to see a backtrace
In addition: There were 34 warnings (use warnings() to see them)
> source("02-build.r") # network construction
House of Representatives 93Error in filter(s, mandate == jj) : object 's' not found
> 
> # have a nice day
> rlang::last_error()
<error>
message: All columns in a tibble must be 1d or 2d objects:
* Column `thomas` is NULL
class:   `rlang_error`
backtrace:
  1. base::source("01-data.r")
  6. base::with.default(...)
  7. [ base::eval(...) ] with 1 more call
  9. tibble::data_frame(...)
 10. tibble::tibble(!(!(!quos(...))))
 11. tibble:::lst_to_tibble(xlq$output, .rows, .name_repair, lengths = xlq$lengths)
 12. tibble:::check_valid_cols(x)
Call `rlang::last_trace()` to see the full backtrace
> rlang::last_trace()
     █
  1. ├─base::source("01-data.r")
  2. │ ├─base::withVisible(eval(ei, envir))
  3. │ └─base::eval(ei, envir)
  4. │   └─base::eval(ei, envir)
  5. ├─base::with(...) 01-data.r:112:2
  6. └─base::with.default(...)
  7.   └─base::eval(substitute(expr), data, enclos = parent.frame())
  8.     └─base::eval(substitute(expr), data, enclos = parent.frame())
  9.       └─tibble::data_frame(...)
 10.         └─tibble::tibble(!(!(!quos(...))))
 11.           └─tibble:::lst_to_tibble(xlq$output, .rows, .name_repair, lengths = xlq$lengths)
 12.             └─tibble:::check_valid_cols(x)
```

**Comment by doctor-phil** [comment]
Sorry, the pasted output did not come out as I expected. Here is a screenshot of the error and backtrace in Rstudio. I had the same issue when running the code from linux command line with Rscript.
![Error](https://user-images.githubusercontent.com/15682144/57810795-a7488d80-7736-11e9-8394-677d7e1f3136.png)

**Comment by briatte** [comment]
Hi @doctor-phil 

This looks like an issue with `tibble` rather than with the code.

Please post you R session info. I cannot guarantee that I'll fix the issue anytime soon, but I'll definitely update the code at some point this year.

**Comment by doctor-phil** [comment]
Thanks! In the meantime, do you know where I could get weighted adjacency matrices for the US senate in the years ~2008-2012? I see them referenced in many academic papers and also the png files on your website so I am hoping you might know. 

If not, no problem. I look forward to the code being updated.

Please see below my R session data:

```
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.2 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] network_1.13.0.1 stringr_1.4.0    dplyr_0.8.1      yaml_2.2.0       jsonlite_1.6    

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1       crayon_1.3.4     assertthat_0.2.1 R6_2.4.0         magrittr_1.5     pillar_1.4.0     stringi_1.3.1    rlang_0.3.4     
 [9] tools_3.4.4      glue_1.3.1       purrr_0.2.5      compiler_3.4.4   pkgconfig_2.0.2  tidyselect_0.2.5 tibble_2.1.1    
```

**Comment by briatte** [comment]
Three solutions:

1. You are running on a an old-ish version of R, so I'd recommend trying my code again with R 3.6.0, even though my code was written a while back.
2. It seems my code gets you what you need, but then fails on older Congressional sessions, so you should be able to edit it to get only 2008-2012.
3. Try checking out the Web pages of James Fowler and Mason Porter -- although AFAIK, their papers relied on data older than 2008.

**Comment by doctor-phil** [comment]
Thanks. In case it helps with future debugging, the problem persists with the newest version of R. Also, by trying different combinations of years in 01-data.r , (114:113, 94:93, 111:108, etc), it seems like the offending `thomas' is present in all years.

I think the Fowler data is too old for what I need. I should be able to use it to make sure I'm at least on the right track, though.

**Comment by briatte** [comment]
Hi @doctor-phil 

Apologies for not giving a more thorough look to your issue earlier.

The issue you face in the code is at this point:

https://github.com/briatte/congress/blob/e3c1707c4a72cdffc09b181257314236744488f2/01-data.r#L98-L112

It looks like the structure of the [YAML file for current U.S. legislators](https://github.com/unitedstates/congress-legislators/blob/master/legislators-current.yaml) has changed. The error happens because the code looks for `id$thomas` and does not find it.

Try replacing line 112 of the code with

```r
y = with(x, data_frame(thomas = ifelse(is.null(id$thomas), NA, id$thomas), icpsr,
```

I'll commit a patch soon-ish.

**Comment by doctor-phil** [comment]
Thank you! This line fixed the issue.
